name: Merge forward release to develop
on:
  push:
    branches:
      - "release"
env: 
  sourceBranchToMerge: release
  targetBranch: develop
  branchForPullRequest: release/mergeReleaseToDevelop
jobs:
  merge-forward-to-develop:
    name: Merge forward to develop
    runs-on: ubuntu-latest
    sourceBranchToMerge = release
    targetBranch: develop
    branchForPullRequest: release/mergeReleaseToDevelop
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Create merge branch if needed
        run: |
          if git branch -r --format "%(refname:short)" | grep "^origin/feature/${branchForPullRequest}$"
            echo "Creating branch ${branchForPullRequest} for pull request"
            # TODO craeate branch
          then
          else
            echo "${branchForPullRequest} allready exists"
          fi
      - name: Merge and 
        run: |
            echo "Merging ${sourceBranchToMerge} -> ${branchForPullRequest}"
            git checkout ${branchForPullRequest}
            git merge ${branchForPullRequest} --no-ff -m "Auto-merge release back to develop"
            git push
      - name: Create pull request
        run: |
          
