name: Merge forward release to develop
on:
  push:
    branches:
      - "release"
env: 
  sourceBranchToMerge: "release"
  targetBranch: "develop"
  branchForPullRequest: "release/mergeReleaseToDevelop"
jobs:
  merge-forward-to-develop:
    name: Merge forward to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Create merge branch if needed
        run: |
          if git branch -r --format "%(refname:short)" | grep "^origin/${branchForPullRequest}$" then
            echo "Creating branch ${branchForPullRequest} for pull request"
            git checkout ${targetBranch}
            git checkout -b ${branchForPullRequest}
          else
            echo "${branchForPullRequest} allready exists"
          fi
      - name: Merge
        run: |
            echo "Merging ${sourceBranchToMerge} -> ${branchForPullRequest}"
            git checkout ${branchForPullRequest}
            git merge ${sourceBranchToMerge} --no-ff -m "Auto-merge release back to develop"
            git push
      - name: createPullRequest
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automatic merge release to develop
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          #team-reviewers: |
          #  codeowners
          milestone: 1
          draft: false
          
