name: Create pull request for merge to develop
on:
  push:
    branches:
      - release__
jobs:
  CreatePullRequestToDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Reset destination branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature/release_merge
          commit-message: "chore: Automerge from release to develop"
          title: "chore: Automatic merge from release to develop" 
          delete-branch: true
