name: Merge forward release to develop
on:
  push:
    branches:
      - "release"
env: 
  sourceBranchToMerge: "release"
  targetBranch: "develop"
  branchForPullRequest: "mergeReleaseToDevelop3"
jobs:
  merge-forward-to-develop:
    name: Merge forward to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Create merge branch if needed
        run: |
          #echo "${{ env.branchForPullRequest }}"
          #if git branch -r --format "%(refname:short)" | grep "^origin/${{ env.branchForPullRequest }}$" then
          echo "Creating branch ${{ env.branchForPullRequest }} for pull request"
          git checkout ${{ env.targetBranch }}
          git checkout -b ${{ env.branchForPullRequest }}
          git push --set-upstream origin ${{ env.branchForPullRequest }}
          #else
          #  echo "${{ env.branchForPullRequest}} allready exists"
          #fi
          #shell: bash
      - name: Merge
        run: |
            echo "Merging ${sourceBranchToMerge} -> ${branchForPullRequest}"
            git checkout ${branchForPullRequest}
            git merge ${sourceBranchToMerge} --no-ff -m "Auto-merge release back to develop"
            git push
      - name: checkoutBranch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branchForPullRequest }}
      - name: createPullRequest
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automatic merge release to develop
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: ${{ env.branchForPullRequest }}
          branch: "Xxx"  
          #${{ env.targetBranch }}
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          #team-reviewers: |
          #  codeowners
          milestone: 1
          draft: false
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
