name: Create pull request for merge to develop
on:
  push:
    branches:
      - release
jobs:
  CreatePullRequestToDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Reset destination branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          branch: feature/release_merge
          commit-message: "chore: Automerge from release to develop"
          title: "chore: Automatic merge from release to develop" 
          delete-branch: true
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Enable automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_METHOD: "rebase"
          PULL_REQUEST: "${{steps.cpr.outputs.pull-request-number}}"
      - name: Auto approve pull request
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
