name: Update endpoints on webApi

on:
  push:
    branches:
      - main

jobs:
  Encode_yaml_to_base64:
    runs-on: ubuntu-latest
    steps:
    - name: Encode file
      run: |
        var=$(echo 'Hello world' | base64)
        echo $var
    - name: Ping
      run: ping uat2-webapi-mila.vs.csin.cz
  

